---
title: "final_project"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Import packages
library(dplyr)
library(janitor)
```

```{r}
# Read CSV
d <- data.frame(read.csv("final.csv"))
```

```{r}
# Select relevant columns
d2 <- d %>% select(StartDate, EndDate, Progress, Finished, Q2.1, Q2.2, Q2.3, Q2.4, Q2.6, Q2.7, Q2.8, Q2.11, Q2.12, Q2.13, Q2.14, Q2.15,
             Q2.16, Q2.17, Q2.18_1, Q2.18_2, Q73.1, Q73.2, Q73.3, Q73.4, Q74.1, Q75.1, Q76.1, Q77.1, Q78.1, Q79.1, Q80.1, Q81.1, Q82.1, 
             Q83.1)
```

```{r}
# Name columns
d2 <- d2 %>% row_to_names(row_number = 1)
```

```{r}
# Remove unwanted 2nd row
d2 <- d2[3:nrow(d2), ]
```

```{r}
# Reset index
row.names(d2) <- NULL
```

```{r}
# Set new column names
new_colnames = c("Start Date", "End Date", "Progress", "Finished", "Birthyear", "Gender", "ESL", "Race", "Country",
                 "State", "Role", "Work", "Employed", "Ann_Income", "Edu_Level", "Pol_Aff", "Religion", "Read", 
                 "Read_SM", "Make_SM", "Open_Elem", "How_Many_Days", "Capacity", "Vacc_Effec", "Chart_Control1", "Chart_Control2",
                 "Chart_Treat1", "Chart_Treat2", "Array_Control1", "Array_Control2", "Array_Control3", "Array_Treat1", "Array_Treat2",
                 "Array_Treat3")


names(d2)[1:34] <- new_colnames
```

```{r}
# Recode Variables for Chart Arm
d2$Chart_Control1 <- recode(d2$Chart_Control1, "for 500 people vaccinated only 50 became infected with COVID-19"="Wrong", 
                            "for 500 people vaccinated only 25 became infected with COVID-19"="Right")
d2$Chart_Control2 <- recode(d2$Chart_Control2, "for 500 people vaccinated only 75 became infected with COVID-19"="Wrong", 
                            "for 500 people vaccinated only 10 became infected with COVID-19"="Right")
d2$Chart_Treat1 <- recode(d2$Chart_Treat1, "IM_bKkswuEiolXdwwu" = "Wrong", "IM_bymouquPLlMsto2" = "Right")
d2$Chart_Treat2 <- recode(d2$Chart_Treat2, "IM_07EKdPsIO5Cidpk" = "Right", "IM_dbuYoG7rE5mWLbM" = "Wrong")

# Recode Variables for Icon Array Arm
d2$Array_Control1 <- recode(d2$Array_Control1, "Yes" = "Right", "No" = "Wrong")
d2$Array_Control2 <- recode(d2$Array_Control2, "Yes" = "Right", "No" = "Wrong")
d2$Array_Control3 <- recode(d2$Array_Control3, "Yes" = "Right", "No" = "Wrong")
d2$Array_Treat1 <- recode(d2$Array_Treat1, "Yes" = "Right", "No" = "Wrong")
d2$Array_Treat2 <- recode(d2$Array_Treat2, "Yes" = "Right", "No" = "Wrong")
d2$Array_Treat3 <- recode(d2$Array_Treat3, "Yes" = "Right", "No" = "Wrong")
```

```{r}
write.csv(d2, "dataset.csv", row.names=FALSE)
```


