---
title: "SP EDA"
output: html_notebook
---

```{r}
library(data.table)

library(sandwich)
library(lmtest)

library(AER) 

library (purrr)

library(ggplot2) 
library(patchwork)
library(stargazer)
library(dplyr)
library(janitor)
library(stringr)
library(gridExtra)
library(pwr)
```

```{r}
d <- data.table(read.csv("dataset_tmp.csv"))
```

```{r}
colnames(d)
```

Simple EDA for demographics:

```{r}
# Remove non-numeric answers in birthyear
d$Birthyear <- gsub("[^0-9.-]", "", d$Birthyear)
# For all birthyears that aren't years, subtract year from 2021 to calculate age
d[, Birthyear := as.double(Birthyear)][Birthyear>=1000, Birthyear:=lapply(Birthyear, function(x){2021-x})]
d[Birthyear<=1, Birthyear:=""]
```
```{r}
# Mean age of Participants
d[, mean(Birthyear, na.rm=TRUE)]
d[, sd(Birthyear, na.rm=TRUE)]

# Describe Age
summary(d$Birthyear)
```

```{r}
#Various Demographics by Education Level
a <- d[, .N, by=Edu_Level]
b <- d[, lapply(.SD, mean, na.rm=TRUE), .SDcols="Birthyear", by="Edu_Level"]
c <- d[(ESL=="Yes"), .N, by=Edu_Level]
e <- d[, lapply(.SD, length), .SDcols="ESL", by=Edu_Level]

demo <- data.table("Educational Level"=a$Edu_Level, "n"=a$N, "%Total"=round((a$N/sum(a$N))*100, 1), "Mean Age"=round(b$Birthyear, 1), "%ESL"=round((c$N/e$ESL)*100, 1))
png("images/demographics.png", height = 2,width = 7,units = "in", res = 72)
p<-tableGrob(demo)
grid.arrange(p)
dev.off()
```

```{r}
#Should elementary schools be open: Opinions
d[, lapply(.SD, length), .SDcols="Open_Elem", by="Open_Elem"]
#How many days?
d[, lapply(.SD, length), .SDcols="How_Many_Days", by="How_Many_Days"]
#What capacity?
d[, lapply(.SD, length), .SDcols="Capacity", by="Capacity"]
#What % Vacc effectiveness
d[, lapply(.SD, length), .SDcols="Vacc_Effec", by="Vacc_Effec"]
```

```{r}
stems <- frame_data(
  ~Question, ~n,
  "Should Elementary Schools be Opened?", "",
  "Yes", "114",
  "No", "150",
  "How Many Days Should Schools Open?", "",
  "None", "110",
  "<5 Weekdays", "116",
  "Mon-Fri", "38",
  "At What Capacity Should Schools Open?", "",
  "25%", "95",
  "50%", "125",
  "75%", "28",
  "100", "16",
  "How Effective Should the Vaccine Be?", "",
  "85%-90%", "98",
  "90%-95%", "96",
  ">95%", "69"
  )

png("images/stems.png", height = 5,width = 5,units = "in", res = 72)
p<-tableGrob(stems)
grid.arrange(p)
dev.off()
```

```{r}
d[, "Chart_Control_Merged" := paste0(Chart_Control1, Chart_Control2)]
d[, "Chart_Treat_Merged" := paste0(Chart_Treat1, Chart_Treat2)]
```

```{r}
d[, "Array_Control_Merged" := paste0(Array_Control1, Array_Control2, Array_Control3)]
d[, "Array_Treat_Merged" := paste0(Array_Treat1, Array_Treat2, Array_Treat3)]
```

```{r}
d[,lapply(.SD, length), .SDcols="Chart_Control_Merged", by="Chart_Control_Merged"]
d[,lapply(.SD, length), .SDcols="Chart_Treat_Merged", by="Chart_Treat_Merged"]
```

```{r}
#Count number of responses for the chart arm
d[(Chart_Control_Merged!=""), .N]
d[(Chart_Treat_Merged!=""), .N]
```
```{r}
# No. of right and wrong responses in chart arm
d[(Chart_Control_Merged!=""), .N, by=Chart_Control_Merged]
d[(Chart_Treat_Merged!=""), .N, by=Chart_Treat_Merged]
```

```{r}
# Percentage correct
chart_control_right <- d[(Chart_Control_Merged=="Right"), .N]
chart_control_wrong <- d[(Chart_Control_Merged=="Wrong"), .N]
chart_treat_right <- d[(Chart_Treat_Merged=="Right"), .N]
chart_treat_wrong <- d[(Chart_Treat_Merged=="Wrong"), .N]
#Control % right:
c_ctrl_pct <- (chart_control_right/(chart_control_right+chart_control_wrong))*100
#Treat % right:
c_trt_pct <- (chart_treat_right/(chart_treat_right+chart_treat_wrong))*100
```


```{r}
# Make matrix with group values
chart = matrix(c(chart_control_right,chart_treat_right,chart_control_wrong,chart_treat_wrong),ncol=2)
chisq.test(chart, correct=F)

#Turn into data frame with labels
chart <- data.frame(chart)
rownames(chart) <- c("Control", "Treat")
colnames(chart) <- c("Right", "Wrong")
chart$`%Right` = c(round(c_ctrl_pct,1),round(c_trt_pct,1))
```

```{r}
# Save image:
png("images/chart_matrix.png", height = 2,width = 4,units = "in", res = 72)
grid.arrange(tableGrob(chart))
dev.off()
```

```{r}
# Count number of responses for the icon arrary arm
d[(Array_Control_Merged!=""), .N]
d[(Array_Treat_Merged!=""), .N]
```

```{r}
# No. of right and wrong responses in array arm
d[(Array_Control_Merged!=""), .N, by=Array_Control_Merged]
d[(Array_Treat_Merged!=""), .N, by=Array_Treat_Merged]
```
```{r}
# Percentage correct
array_control_right <- d[(Array_Control_Merged=="Right"), .N]
array_control_wrong <- d[(Array_Control_Merged=="Wrong"), .N]
array_treat_right <- d[(Array_Treat_Merged=="Right"), .N]
array_treat_wrong <- d[(Array_Treat_Merged=="Wrong"), .N]
#Control % right:
a_ctrl_pct <- (array_control_right/(array_control_right+array_control_wrong))*100
#Treat % right:
a_trt_pct <- (array_treat_right/(array_treat_right+array_treat_wrong))*100
```

```{r}
# Make matrix with group values
arr = matrix(c(array_control_right,array_treat_right,array_control_wrong,array_treat_wrong),ncol=2)
chisq.test(arr, correct=F)

#Turn into data frame with labels
array <- data.frame(arr)
rownames(array) <- c("Control", "Treat")
colnames(array) <- c("Right", "Wrong")
array$`%Right` = c(round(a_ctrl_pct,1),round(a_trt_pct,1))
```


```{r}
# expected power:
j<-pwr.2p.test(h = ES.h(p1 = 0.86, p2 = 0.80), sig.level = 0.05, power = .80)
plot(j)
```

```{r}
# How well powered were our actual tests:
pwr.2p2n.test(h = 0.1603, n1 = 135, n2 = 128, sig.level = 0.05)
pwr.2p2n.test(h = 0.1603, n1 = 133, n2 = 119, sig.level = 0.05)
```

```{r}
# How well powered were our actual tests:
pwr.2p2n.test(h = 0.1603, n1 = 136, n2 = 128, sig.level = 0.05)
```

```{r}
# Save image:
png("images/array_matrix.png", height = 2,width = 4,units = "in", res = 72)
grid.arrange(tableGrob(array))
dev.off()
```


```{r}
pilot <- fread("pilot_data.csv")

pilot[, "Chart_Control_Merged" := paste0(Chart_Control1, Chart_Control2)]
pilot[, "Chart_Treat_Merged" := paste0(Chart_Treat1, Chart_Treat2)]

pilot[, "Array_Control_Merged" := paste0(Array_Control1, Array_Control2, Array_Control3)]
pilot[, "Array_Treat_Merged" := paste0(Array_Treat1, Array_Treat2, Array_Treat3)]

pc_control_right <- pilot[(Chart_Control_Merged=="Right"), .N]
pc_control_wrong <- pilot[(Chart_Control_Merged=="Wrong"), .N]
pc_treat_right <- pilot[(Chart_Treat_Merged=="Right"), .N]
pc_treat_wrong <- pilot[(Chart_Treat_Merged=="Wrong"), .N]

pa_control_right <- pilot[(Array_Control_Merged=="Right"), .N]
pa_control_wrong <- pilot[(Array_Control_Merged=="Wrong"), .N]
pa_treat_right <- pilot[(Array_Treat_Merged=="Right"), .N]
pa_treat_wrong <- pilot[(Array_Treat_Merged=="Wrong"), .N]

#Chart Control % right:
pc_ctrl_pct <- (pc_control_right/(pc_control_right+pc_control_wrong))*100
#Chart Treat % right:
pc_trt_pct <- (pc_treat_right/(pc_treat_right+pc_treat_wrong))*100

#Array Control % right:
pa_ctrl_pct <- (pa_control_right/(pa_control_right+pa_control_wrong))*100
#Array Treat % right:
pa_trt_pct <- (pa_treat_right/(pa_treat_right+pa_treat_wrong))*100
```

```{r}
pc_control_right
pc_control_wrong
pc_treat_right
pc_treat_wrong
```

```{r}
# Make matrix with group values
pc = matrix(c(pc_control_right,pc_treat_right,pc_control_wrong,pc_treat_wrong),ncol=2)

#Turn into data frame with labels
p <- data.frame(pc)
rownames(p) <- c("Control", "Treat")
colnames(p) <- c("Right", "Wrong")
p$`%Right` = c(round(pc_ctrl_pct,1),round(pc_trt_pct,1))

# Save image:
png("images/pilot_chart_matrix.png", height = 2,width = 4,units = "in", res = 72)
grid.arrange(tableGrob(p))
dev.off()
```

```{r}
# Make matrix with group values
pa = matrix(c(pa_control_right,pa_treat_right,pa_control_wrong,pa_treat_wrong),ncol=2)

#Turn into data frame with labels
p <- data.frame(pa)
rownames(p) <- c("Control", "Treat")
colnames(p) <- c("Right", "Wrong")
p$`%Right` = c(round(pa_ctrl_pct,1),round(pa_trt_pct,1))

# Save image:
png("images/pilot_array_matrix.png", height = 2,width = 4,units = "in", res = 72)
grid.arrange(tableGrob(p))
dev.off()
```
